### ISSUE TITLE
Public holidays

### ISSUE THREAD

**Issue by camroach87** [camroach87/pr1c3_f0r3c457#1]
Need a file for public holidays. Can then add a dummy variable, or merge with weekend variables to account for drops. Of course, need to check for significance first.

**Comment by cooldudeno1** [comment]
Hello Cam,

Yikes, sorry. Things have been really hectic and I haven't had a chance to
look at this at all really. I should have a chance to kick out a solid
block of work this weekend, though.

Dave C

On Wed, Mar 2, 2016 at 8:45 PM, Cameron Roach <notifications@github.com>
wrote:

> Need a file for public holidays. Can then add a dummy variable, or merge
> with weekend variables to account for drops. Of course, need to check for
> significance first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camroach87/PriceForecast/issues/1>.
>



-- 
David J Collins
Postdoctoral Research Fellow
Singapore University of Technology and Design (SUTD)
www.davidjohncollins.com

**Comment by camroach87** [comment]
It's ok - I figured you were busy. I just like using this fancy issue logger. oooohhhh header text

# Dave is dumb

nice! markup!

> awefawveawevawevga

Also it's really easy to find this repo... I might rename it so no-one can steal our awesome ideas.

**Comment by camroach87** [comment]
btw - have a look at my testModels.py file. It shows how to load data and fit models. It's pretty simple, but should give you an idea of how to do things. I spent quite a bit of time trying to figure out how to do things the "right" way rather than just hacking things together (although it's still a little bit hacky)
